### ISSUE TITLE
As a user, I want to be able to see a photo first and foremost when I click on its page.

### ISSUE THREAD

**Issue by jhbell** [flpymonkey/idb#116]
Estimated time: 1 hour
Actual time: 1 hour

**Comment by tonydenapoli** [comment]
Some of us would like the photo to be next to the description. Others would like the description below the photo. I went with putting the description below the photo

**Comment by jhbell** [comment]
We are going to compromise on this and put the links to the other items underneath the photo so that the layout is something like the following:
```
        [ photo ]
          title

Author            Link to Camera
Date
Likes             Link to Park

Description ...........
............
```

**Comment by tonydenapoli** [comment]
I think we finally came to an agreement!

**Comment by dayannyc** [comment]
Having photo first definitely captures the user's attention!
