### ISSUE TITLE
As a user, I'd like to see the picture of the camera itself without it being stretched

### ISSUE THREAD

**Issue by jhbell** [flpymonkey/idb#118]
This would give an accurate view of its size and shape.

Estimated time: 2 hours
Actual time: 3 hours

**Comment by jhbell** [comment]
https://stackoverflow.com/questions/16310918/css-scale-and-square-center-crop-image
OR
We can just set a max-height for the image

**Comment by jhbell** [comment]
@vargasbri2 @tonydenapoli @dayannyc Right now the image will always fit, but the cards aren't the same height. I think this might be good to close and we can do #92 to improve.

If we complete #92 then we can maybe set the card height to be 100% and then they'd be the same height even though the images might be smaller.

**Comment by jhbell** [comment]
Closed with 6697bee

**Comment by tonydenapoli** [comment]
have the width be auto

**Comment by dayannyc** [comment]
Make sure to cover really long and wide photos.
