### ISSUE TITLE
As a user, I want to be able to easily tell the number of total commits/unit tests/issues are.

### ISSUE THREAD

**Issue by jhbell** [flpymonkey/idb#120]
The numbers are there, but it's not aligned with the text.

Estimated time: 5 minutes
Actual time: 5 minutes

**Comment by jhbell** [comment]
This is a resizing issue where things aren't in the same row. Fixing...

**Comment by jhbell** [comment]
Added a break between rows and re-organized bootstrap grid.

**Comment by tonydenapoli** [comment]
breaks between divs allow for consistent spacing

**Comment by dayannyc** [comment]
Looks much better!
