### ISSUE TITLE
As a user, I want searching to work properly when I don't enter anything or only enter spaces

### ISSUE THREAD

**Issue by jhbell** [flpymonkey/idb#123]
For example, searching with an obscene amount of spaces is still a valid search: http://natphoto.me/search?q=+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Estimated time: 1 hour
Actual time: 30 minutes

**Comment by tonydenapoli** [comment]
Maybe limit the amount of characters you can search by?

**Comment by dayannyc** [comment]
Searching by emojis would be nice.
