### ISSUE TITLE
As a user, I don't want to click on broken links.

### ISSUE THREAD

**Issue by jhbell** [flpymonkey/idb#124]
http://natphoto.me/parks/Haleakal&#257;%20National%20Park

Estimated time: 15 minutes
Actual time: 30 minutes

**Comment by jhbell** [comment]
Resolved by removing that park from the database. This park in particular never got any photos due to the special character in the name, so the park itself was an anomaly.

**Comment by flpymonkey** [comment]
We ended up adding it back with the correct information to satisfy our unit tests and have more complete data on all national parks.

**Comment by flpymonkey** [comment]
We fixed this with cameras by having a default camera page that will render for cameras that we don't have in our database.
