### ISSUE TITLE
As a user, I want the search query to be highlighted more noticeably.

### ISSUE THREAD

**Issue by jhbell** [flpymonkey/idb#125]
Estimated Time: 30 minutes
Actual Time: 30 minutes

**Comment by jhbell** [comment]
I think we can just do a yellow highlight with black, bold, text. Should be as easy as changing the CSS

**Comment by jhbell** [comment]
Fixed via commit 5e2e8e0256402818865e29cae3a9add14a8b2425

**Comment by dayannyc** [comment]
Maybe highlight with the green we use?

**Comment by tonydenapoli** [comment]
I also prefer green to be consistent
