### ISSUE TITLE
 As a user, I would like to use filter tags to search for particular photos

### ISSUE THREAD

**Issue by jhbell** [flpymonkey/idb#126]
I would like to have a "wildlife" tag implemented as a photos filter to see all tagged as "wildlife". 

Estimated time: wontfix
Actual time: wontfix

**Comment by flpymonkey** [comment]
@yvonneKim @zibbycakes @ijiang @calebROlson We only have hashtags in a few of our image descriptions and titles (like only ~20 tagged images in total), is this what you want us to filter by? Or are you asking for us to go through and tag all of our images for filtering (we do not currently have this information and will most likely have to do it manually)?

**Comment by calebROlson** [comment]
If you don't have tags then you shouldn't have to add them manually. I commented on Piazza too, but you should probably just skip this story. There are 10 others, anyway. Sorry for the confusion.

**Comment by jhbell** [comment]
Ah okay. Thanks for the clarification!
