### ISSUE TITLE
As a user I would like to add an /all endpoint to the API to be used for filtering in the front end

### ISSUE THREAD

**Issue by flpymonkey** [flpymonkey/idb#64]
Need to be able to search by keyword
Estimated time: 2 hours
Acutal Time: 3 hours

**Comment by jhbell** [comment]
We aren't going to do this in the API, we are going to instead add an `/all` endpoint to the API and search in the frontend

**Comment by jhbell** [comment]
This is complete as of commit 4801aaeaafc58269337e37bb65662ad229f2b52b

**Comment by tonydenapoli** [comment]
We can use your /all api to filter, instead of using the api's for each model

**Comment by flpymonkey** [comment]
WOW THIS IS AMAZING
