### ISSUE TITLE
As a user, I want to see at least 9 instances of cameras on the site

### ISSUE THREAD

**Issue by jhbell** [flpymonkey/idb#72]
Estimated time: 6 hours
Actual time: 8 hours

**Comment by flpymonkey** [comment]
Camera data is at
api.natphoto.me/cameras
and is filterable using 
?park="Big Bend National Park"

**Comment by flpymonkey** [comment]
DONE!

**Comment by tonydenapoli** [comment]
Would a common camera user want to search more for price of megapixels?
