### ISSUE TITLE
As a user, I want to see at least 9 instances of national parks on the site

### ISSUE THREAD

**Issue by jhbell** [flpymonkey/idb#73]
Estimated Time: 6 hours
Actual Time: 8 hours

**Comment by flpymonkey** [comment]
Added the API endpoint to get all parks at 
api.natphoto.me/parks

**Comment by flpymonkey** [comment]
Can also filter the parks by camera using
api.natphoto.me/parks?camera=<camera_name>

**Comment by flpymonkey** [comment]
Front end is now pulling data for grid! GOOD JOB GUYS!
