### ISSUE TITLE
As a user, I want to see at least 12 instances of photograph instances on the site.

### ISSUE THREAD

**Issue by jhbell** [flpymonkey/idb#74]
Estimated time: 6 hours
Actual time: 15 hours

**Comment by jhbell** [comment]
photograph instances have been scraped via flpymonkey/idb_scraper and put into the database

**Comment by flpymonkey** [comment]
Looks good! :)

**Comment by tonydenapoli** [comment]
Should we highlight the photo itself or more of the info?

**Comment by flpymonkey** [comment]
No Tony

**Comment by flpymonkey** [comment]
But good idea.
