### ISSUE TITLE
As a user, I would like a RESTful API implemented and tested with Postman

### ISSUE THREAD

**Issue by jhbell** [flpymonkey/idb#75]
Estimated time: 10 hours
Actual time: 12 hours

**Comment by flpymonkey** [comment]
Using Flask-RESTful

**Comment by flpymonkey** [comment]
API set up at api.natphoto.me
Endpoints include:
api.natphoto.me/cameras
api.natphoto.me/photos
api.natphoto.me/parks
api.natphoto.me/cameras/<camera_id>
api.natphoto.me/parks/<park_name>

**Comment by tonydenapoli** [comment]
Fetching three times in necessary now, but maybe we should optimize it in the future
