### ISSUE TITLE
As a user, I would like to be able to filter each model by at least 3 different attributes.

### ISSUE THREAD

**Issue by jhbell** [flpymonkey/idb#76]
Estimated time: 20 hours
Actual time: 15 hours

**Comment by jhbell** [comment]
I believe filtering has been completed... Is this correct, @dayannyc and @tonydenapoli?

**Comment by jhbell** [comment]
Completed!

**Comment by tonydenapoli** [comment]
We need to add another attribute to filter by.

**Comment by tonydenapoli** [comment]
Filtering should be generalized for all dropdowns and not be specific
