### ISSUE TITLE
As a user, I would like to be able to search across all models

### ISSUE THREAD

**Issue by jhbell** [flpymonkey/idb#78]
Estimated time: 20 hours
Actual time: 18 hours

**Comment by jhbell** [comment]
This should be done in the frontend to prevent having to make a request every time the search parameters change

**Comment by jhbell** [comment]
Searching should actually be done across all models

**Comment by jhbell** [comment]
Results are highlighted and pretty as of 8706ef79f5a71806f862d1ed13e0d17d9fb1dba2

**Comment by tonydenapoli** [comment]
Searching should be done across all attributes of all models

**Comment by flpymonkey** [comment]
We are searching across all attributes of the models!
